name: windows-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: ['labeled', 'opened', 'synchronize', 'reopened']

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      BOOST_ROOT: C:\local\boost_1_82_0
    if: |
      github.repository == 'azerothcore/azerothcore-wotlk'
      && !github.event.pull_request.draft
      && (github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'run-build') || github.event.label.name == 'run-build')
    steps:
      - uses: actions/checkout@v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.9
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh install-deps
      - name: Process pending sql
        shell: bash
        run: bash bin/acore-db-pendings
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build
      - name: Copy dll files
        shell: bash
        run: |
          cp "/c/Program Files/OpenSSL/bin/legacy.dll" "env/dist"
      - name: Dry run authserver
        shell: bash
        run: |
          source ./apps/ci/ci-gen-server-conf-files.sh "authserver" "configs" "."
          cd env/dist
          ./authserver -dry-run
      - name: Dry run worldserver
        shell: bash
        run: |
          source ./apps/ci/ci-gen-server-conf-files.sh "worldserver" "configs" "."
          cd env/dist
          ./worldserver -dry-run
      - name: Stop MySQL
        run: net stop mysql
